### ISSUE TITLE
Volumeeditor can't display arbitrary slicings

### ISSUE THREAD

**Issue by bekaus** [ilastik/volumina#119]
- We should be able to handle every desired slice projection.
  Currently the volumeeditor is hardwirded to show slicings of axes 1,2,3 .
  The pixelpipeline supports any slicing.
  Enable that feature because it is needed for certain multidimensional datasets.
- Need to take axis colors also into consideration

**Comment by k-dominik** [comment]
I guess we won't fix it. Should we close it, @akreshuk?

**Comment by akreshuk** [comment]
too much work and more important things are broken.

**Comment by bekaus** [comment]
😭
