### ISSUE TITLE
Time slider visible for data with no time

### ISSUE THREAD

**Issue by akreshuk** [ilastik/volumina#161]
The time slider introduced when the learning branch was merged is visible for regular images as well. First, it shouldn't be visible in this case, second, it should have a tooltip when it is visible.

**Comment by ilastikdev** [comment]
see https://github.com/ilastik/volumina/pull/162

**Comment by ilastikdev** [comment]
to work for other workflows than structured learning one needs only this update of volumina

to work in structured learning one needs also the latest commit of the learning branch
https://github.com/ilastik/ilastik/commit/6a839034163054488dee25cad42292a1a95559ca
